site_name: wdl-docs
theme:
  name: readthedocs
  include_homepage_in_sidebar: true
  navigation_depth: 4
  highlightjs: true

nav:
  - Home: 'index.md'
  - Getting Started with WDL:
    - 'Base structure': 'Base_structure.md'
    - 'Add variables': 'add_variables.md'
    - 'Add plumbing': 'add_plumbing.md'
    - 'Validate syntax': 'validate_syntax.md'
    - 'Specify inputs': 'specify_inputs.md'
    - 'Execute!': 'execute.md'
    - 'Toolkit: All the tools you need to write and run WDLs': 'toolkit.md'
  - WDL Plumbing Options:
    - 'Linear chaining': 'Linear_chaining.md'
    - 'Branch and merge': 'Branch_and_merge.md'
    - 'Multi-input/Multi-output': 'MultiInput_MultiOutput.md'
    - 'Scatter-gather parallelism': 'ScatterGather_parallelism.md'
    - 'Task aliasing': 'task_aliasing.md'
    - 'Conditional (if/else)': 'conditionals.md'
  - 'WDL Script Components':
    - 'workflow': 'workflow.md'
    - 'call': 'call.md'
    - 'task': 'task.md'
    - 'command': 'command.md'
    - 'output': 'output'
    - 'parameter_meta': 'parameter_meta.md'
    - 'meta': 'meta.md'
    - 'basename': 'basename.md'
    - 'Variable types in WDL': 'variable_types.md'
  - 'WDL Best Practices for Google Cloud':
    - 'WDL cost optimization: Tips and tricks when working with Google Cloud in Terra': 'GC_cost_optimization.md'
  - 'WDL Cookbook: Code snippets':
    - 'Running conditional tasks based on input size': 'conditionals_input_size.md'